# .github/workflows/update-from-template.yml
name: Update from Template

on:
  workflow_dispatch:  # 👈 enables manual trigger from GitHub UI

jobs:
  sync-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add template repo as remote
        run: |
          git remote add template https://github.com/Petlja/PLCT_template
          git fetch template

      - name: Merge template changes
        run: |
          git merge template/main --allow-unrelated-histories || true

      - name: Push changes
        run: |
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}